name: Build WPF App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore ExcelToSqlExporter.csproj

    - name: Build application
      run: dotnet build ExcelToSqlExporter.csproj --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish ExcelToSqlExporter.csproj -c Release -r win-x64 --self-contained true --no-build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExcelToSqlExporter
        path: bin/Release/net10.0-windows/win-x64/publish
